<?php
/**
 * Implements hook_block_info().
 */
function custom_hooks_block_info() {
  $blocks = array();
  $blocks['tabbed_content'] = array(
    'info' => t('Tabbed Content Home'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}


/**
 * Implements hook_block_view().
 */
function custom_hooks_block_view($delta) {
  $variables = '';
  $block     = array();
  // menu
  if ($delta == 'tabbed_content') {
    $block['subject'] = '<none>';
    $block['content'] = theme('custom_tabbed_content_template', $variables);
  }
  return $block;
}


/**
 * Get nid for Ticket pages.
 *  
 */
function get_nid_tabbed_content_homepage() {
  $query = db_select('node', 'n');
  $query->fields('n', array(
    'nid'
  ));
  $query->condition('n.type', 'tabbed_content_home');
  $result = $query->execute()->fetchAll();
  foreach ($result as $value) {
    $node[] = node_load($value->nid); // $value contains the node id
  }
  return $node;
}


/**
 * Implements hook_theme().
 */
function custom_hooks_theme() {
  return array(
    'custom_tabbed_content_template' => array(
      'template' => 'tabbed_content',
      'variables' => array()
    )
  );
}

function getTabbedContentImage($nid) {
  $images = '';
  $img    = '';
  $node   = node_load($nid);
  if (isset($node->field_tabbed_content_home_image['und'])) {
    $images[] = $node->field_tabbed_content_home_image['und'];
  }
    if (isset($node->field_tabbed_content_home_link['und'])) {
    $link[] = $node->field_tabbed_content_home_link['und'];
  }
  foreach ((array) $images as $val) {
    foreach ((array) $val as $key=>$value) {
      $uri[$key]['uri'] = $value['uri'];
      $uri[$key]['title'] = $value['title'];
    }
  }
foreach ((array) $link as $val) {
    foreach ((array) $val as $value) {
      $links[] = $value['url'];
    }
  }
   foreach ($links as $key => $value) {
     $uri[$key]['link'] = $value;
   }
    foreach ($uri as $key=>$value) {
      if (isset($value['uri'])) {
        $img_url = $value['uri'];
        $image = image_style_url("our_research_style_150x150",$img_url);
        $img .= '<li> <a href="our-research#'.$value['link'].'"><i><img src= "' . $image . '"></i><p class="txt-btm home-icon-title">'.$value['title'].'</p></a></li>';
      }
    }
  if ($img) {
    return $imglst = '<ul class="list font-alt">' . $img . '</ul>';
  }
}

/**
 * Implements hook_preprocess_node()
 */
function custom_hooks_preprocess_node(&$vars) {
  $node = $vars['node'];
  $tid = $node->field_team_type['und'][0]['tid'];
  $type = $node->type;
  if ($type == 'news' || $type == 'team') {
    $query = db_select('node', 'n');
    if ($type == 'team') {
      $query->innerjoin('field_data_field_team_type', 'f', 'f.entity_id = n.nid');
    }
    $query->fields('n', array('nid'));
    $query->condition('n.type', $type);
    if ($type == 'team') {
      $query->condition('f.field_team_type_tid', $tid);
    }
    $query->condition('created', $node->created,'>');
    $query->orderBy('created', 'AESC');
    $query->range(0,1);
    $resultNext = $query->execute()->fetchAll();
    if ($type == 'news') {
      if($resultNext[0]->nid){
        $vars['nextPage'] ='<div class="next-post pull-right">'.l('NEXT POST','node/'.$resultNext[0]->nid).'</div>';
      }
    }elseif ($type == 'team') {
      if($resultNext[0]->nid){
        $vars['teamNextPage'] ='<div class="next-post team-pagination">'.l('NEXT','node/'.$resultNext[0]->nid).'<i class="fa fa-caret-right"></i></div>';
      }
    }
    $query = db_select('node', 'n');
    if ($type == 'team') {
      $query->innerjoin('field_data_field_team_type', 'f', 'f.entity_id = n.nid');
    }
    $query->fields('n', array('nid'));
    $query->condition('n.type', $type);
    if ($type == 'team') {
      $query->condition('f.field_team_type_tid', $tid);
    }
    $query->condition('created', $node->created,'<');
    $query->orderBy('created', 'DESC');
    $query->range(0,1);
    $resultPrevious = $query->execute()->fetchAll();
    print_r($resultPrevious);
    if ($type == 'news') {
      if($resultPrevious[0]->nid){
        $vars['previousPage'] = '<div class="previous-post pull-left">'.l('PREVIOUS POST','node/'.$resultPrevious[0]->nid).'</div>';
      }
    }elseif ($type == 'team') {
      if($resultPrevious[0]->nid){
        $vars['teamPreviousPage'] ='<div class="previous-post team-pagination"><i class="fa fa-caret-left"></i>'.l('PREVIOUS','node/'.$resultPrevious[0]->nid).'</div>';
      }
    }
  } 
}